### ISSUE TITLE
[build]: TopLevelParameterNameAnalyzer throws NullReferenceException

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#712]
We've been seeing the following warnings when building the **neonKUBE** solution for several months now.  I've tried some random things to attempt to fix this without luck:
```
CSC : warning AD0001: Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```
I just Googled this again and see that MSFT acknowledges this as a .NET Core 2.2 vs. 3.0 conflict:

https://github.com/aspnet/AspNetCore/issues/14723

This shouldn't apply to us because our test projects are targeting .NET Core 3.0.  It does sound like MSFT is going to try mitigating this behavior though.

I'm going to put this on the backlog and take another look after the first .NET Core 3.0 upgrade.

**Comment by bentorkia** [comment]
I got the same warning when I migrated my application to 3.0. It is a conflict between 
Microsoft.AspNetCore.Mvc.Analyzers and Microsoft.AspNetCore.Analyzers.
Deleting the 'bin' and 'obj' folder should solve this problem.

**Comment by jefflill** [comment]
Unfortunately, we've tried that and it didn't help.  Over the past few months I've even recreated workstations from scratch (reinstalled Windows for other reasons) and we're still seeing this.

I briefly tried to install the new analyzers but we ended up with thousands and thousands of warnings and I didn't have time to sort things out then.  I'll have to devote some more time to this soon.

**Comment by jefflill** [comment]
Most of these warnings disappeared after updating a couple dozen nuget package references.  We're still seeing this for one project:

**Test.Neon.ModelGen**

I compared the package references to another project that doesn't have the warnings and don't see anything obvious.  I'll need to come back and revisit this.

**Comment by jefflill** [comment]
**FIXED:** OK, that was stupid.  I needed to stop referencing old ASPNET 2.x packages and reference the **Microsoft.AspNetCore.App** meta-package instead as described here:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-3.1&tabs=visual-studio
